"""add background_agent background_agent_run and trigger tables

Revision ID: 376c405af092
Revises: 4a89cffd93d5
Create Date: 2026-03-28 01:12:12.588994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "376c405af092"
down_revision: str | Sequence[str] | None = "4a89cffd93d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("engine", sa.Enum("INTERNAL", "CLAUDE_CODE", "GEMINI_CLI", name="agentengine"), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_background_agents_project_id"), "background_agents", ["project_id"], unique=False)
    op.create_table(
        "background_agent_event_triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("event_type_pattern", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["background_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_agent_event_triggers_agent_id"),
        "background_agent_event_triggers",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "background_agent_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("triggered_by", sa.String(length=255), nullable=False),
        sa.Column("trigger_event_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="backgroundagentrunstatus"),
            nullable=False,
        ),
        sa.Column("state_before", sa.JSON(), nullable=False),
        sa.Column("state_after", sa.JSON(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["background_agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_background_agent_runs_agent_id"), "background_agent_runs", ["agent_id"], unique=False)
    op.create_table(
        "background_agent_schedule_triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("cron_expression", sa.String(length=255), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["background_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_agent_schedule_triggers_agent_id"),
        "background_agent_schedule_triggers",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "background_agent_mcp_tools",
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("mcp_tool_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["background_agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mcp_tool_id"], ["mcp_tools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id", "mcp_tool_id"),
        sa.UniqueConstraint("agent_id", "mcp_tool_id", name="uq_background_agent_mcp_tool"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("background_agent_mcp_tools")
    op.drop_index(
        op.f("ix_background_agent_schedule_triggers_agent_id"), table_name="background_agent_schedule_triggers"
    )
    op.drop_table("background_agent_schedule_triggers")
    op.drop_index(op.f("ix_background_agent_runs_agent_id"), table_name="background_agent_runs")
    op.drop_table("background_agent_runs")
    op.drop_index(op.f("ix_background_agent_event_triggers_agent_id"), table_name="background_agent_event_triggers")
    op.drop_table("background_agent_event_triggers")
    op.drop_index(op.f("ix_background_agents_project_id"), table_name="background_agents")
    op.drop_table("background_agents")
    # ### end Alembic commands ###
