"""Add unique constraint on codebase.name

Revision ID: 3dfe82baafd9
Revises: dbde08e3eacf
Create Date: 2025-11-14 02:47:59.215751

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dfe82baafd9"
down_revision: str | Sequence[str] | None = "dbde08e3eacf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "codebases", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "codebases", type_="unique")
    # ### end Alembic commands ###
