"""Add conversations table with polymorphic associations

Revision ID: 536d3adbb0a8
Revises: dc1ed364140a
Create Date: 2025-09-25 00:19:43.917649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '536d3adbb0a8'
down_revision: Union[str, Sequence[str], None] = 'dc1ed364140a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_entity_type', sa.String(), nullable=False),
    sa.Column('parent_entity_id', sa.Integer(), nullable=False),
    sa.Column('parent_conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_entity_type', 'parent_entity_id', 'parent_conversation_id', name='uq_one_conversation_per_entity')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('USER_PROMPT', 'TOOL_RESULT', 'TOOL_CALL', 'TEXT_RESPONSE', 'STRUCTURED_RESPONSE', name='messagetype'), nullable=False),
    sa.Column('pydantic_content', sa.JSON(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_conversation_messages')
    op.drop_table('task_conversation_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_conversation_messages',
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('pydantic_content', sqlite.JSON(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_conversation_messages',
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('pydantic_content', sqlite.JSON(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('conversation_messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
