"""Initial migration with document model

Revision ID: 600a189b5b74
Revises: 
Create Date: 2025-09-10 23:39:16.005458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600a189b5b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codebases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.String(length=512), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('context_provider_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('resource_uri', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_uri')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['details_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_codebase_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('codebase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codebase_id'], ['codebases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'codebase_id')
    )
    op.create_table('project_context_resources',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['context_provider_resources.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'resource_id')
    )
    op.create_table('project_conversation_messages',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('USER_PROMPT', 'TOOL_RESULT', 'TOOL_CALL', 'TEXT_RESPONSE', 'STRUCTURED_RESPONSE', name='messagetype'), nullable=False),
    sa.Column('pydantic_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('codebase_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remote_task_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('implementation_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['codebase_id'], ['codebases.id'], ),
    sa.ForeignKeyConstraint(['implementation_plan_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_context_resources',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['context_provider_resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    op.create_table('task_conversation_messages',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('USER_PROMPT', 'TOOL_RESULT', 'TOOL_CALL', 'TEXT_RESPONSE', 'STRUCTURED_RESPONSE', name='messagetype'), nullable=False),
    sa.Column('pydantic_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_conversation_messages')
    op.drop_table('task_context_resources')
    op.drop_table('tasks')
    op.drop_table('project_conversation_messages')
    op.drop_table('project_context_resources')
    op.drop_table('project_codebase_association')
    op.drop_table('projects')
    op.drop_table('documents')
    op.drop_table('context_provider_resources')
    op.drop_table('configurations')
    op.drop_table('codebases')
    # ### end Alembic commands ###
