"""Add git branch fields to Task model

Revision ID: bc33326dcc47
Revises: 3dfe82baafd9
Create Date: 2025-11-14 18:56:19.228819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc33326dcc47"
down_revision: str | Sequence[str] | None = "3dfe82baafd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worktree_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codebase_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("is_main_repo", sa.Boolean(), nullable=False),
        sa.Column("locked_by_task_id", sa.Integer(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("current_branch", sa.String(length=255), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_by_task_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["codebase_id"],
            ["codebases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_used_by_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["locked_by_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("branch_name", sa.String(length=255), nullable=True))
    op.add_column(
        "tasks", sa.Column("branch_mode", sa.Enum("CREATE_NEW", "USE_EXISTING", name="branchmode"), nullable=True)
    )
    op.add_column("tasks", sa.Column("base_branch", sa.String(length=255), nullable=False, server_default="main"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "base_branch")
    op.drop_column("tasks", "branch_mode")
    op.drop_column("tasks", "branch_name")
    op.drop_table("worktree_slots")
    # ### end Alembic commands ###
