"""Add MERGED task status

Revision ID: c180425c7c71
Revises: 517f858134b3
Create Date: 2026-06-10 14:38:49.924911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c180425c7c71"
down_revision: str | Sequence[str] | None = "517f858134b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    for table_name in ("project_context_resources", "context_provider_resources", "task_context_resources"):
        if table_name in existing_tables:
            op.drop_table(table_name)

    # SQLite stores enums as strings without a CHECK constraint (create_constraint
    # defaults to False), so no column alteration is needed there; only run these
    # for backends with native enum support (e.g. PostgreSQL).
    if op.get_bind().dialect.name != "sqlite":
        op.alter_column(
            "custom_field_definitions",
            "entity_type",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum("PROJECT", "TASK", "CODEBASE", "BACKGROUND_AGENT", name="entitytype"),
            existing_nullable=False,
            existing_server_default=sa.text("'TASK'"),
        )
        op.alter_column(
            "implementation_steps",
            "status",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "PENDING", "RUNNING", "COMPLETE", "FAILED", "SKIPPED", "INTERRUPTED", name="implementationstepstatus"
            ),
            existing_nullable=False,
        )
        op.alter_column(
            "tasks",
            "status",
            existing_type=sa.Enum("PLANNING", "IMPLEMENTING", "PR_OPEN", "COMPLETE", name="taskstatus"),
            type_=sa.Enum("PLANNING", "IMPLEMENTING", "PR_OPEN", "MERGED", "COMPLETE", name="taskstatus"),
            existing_nullable=False,
            existing_default="planning",
        )

    inspector = sa.inspect(op.get_bind())
    existing_index_names = {idx["name"] for idx in inspector.get_indexes("worktree_slots")}
    with op.batch_alter_table("worktree_slots") as batch_op:
        if op.f("uq_worktree_slot_path") in existing_index_names:
            batch_op.drop_index(op.f("uq_worktree_slot_path"))
        batch_op.create_unique_constraint("uq_worktree_slots_path", ["path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worktree_slots") as batch_op:
        batch_op.drop_constraint("uq_worktree_slots_path", type_="unique")
        batch_op.create_index(op.f("uq_worktree_slot_path"), ["path"], unique=True)

    if op.get_bind().dialect.name != "sqlite":
        op.alter_column(
            "tasks",
            "status",
            existing_type=sa.Enum("PLANNING", "IMPLEMENTING", "PR_OPEN", "MERGED", "COMPLETE", name="taskstatus"),
            type_=sa.Enum("PLANNING", "IMPLEMENTING", "PR_OPEN", "COMPLETE", name="taskstatus"),
            existing_nullable=False,
            existing_default="planning",
        )
        op.alter_column(
            "implementation_steps",
            "status",
            existing_type=sa.Enum(
                "PENDING", "RUNNING", "COMPLETE", "FAILED", "SKIPPED", "INTERRUPTED", name="implementationstepstatus"
            ),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )
        op.alter_column(
            "custom_field_definitions",
            "entity_type",
            existing_type=sa.Enum("PROJECT", "TASK", "CODEBASE", "BACKGROUND_AGENT", name="entitytype"),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
            existing_server_default=sa.text("'TASK'"),
        )

    op.create_table(
        "task_context_resources",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column("resource_id", sa.INTEGER(), nullable=False),
        sa.Column("added_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["context_provider_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "resource_id"),
    )
    op.create_table(
        "context_provider_resources",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("provider_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("resource_uri", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("description", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_uri"),
    )
    op.create_table(
        "project_context_resources",
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("resource_id", sa.INTEGER(), nullable=False),
        sa.Column("added_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["context_provider_resources.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "resource_id"),
    )
    # ### end Alembic commands ###
