"""add_external_session_id_index

Revision ID: c24bd7de48cc
Revises: ff3d9460b920
Create Date: 2026-03-07 12:15:17.173803

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c24bd7de48cc"
down_revision: str | Sequence[str] | None = "ff3d9460b920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_conversation_external_session_id", "conversations", ["external_session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_conversation_external_session_id", table_name="conversations")
    # ### end Alembic commands ###
