"""Replace Project.current_status with Project.description

Revision ID: d7f5867373fc
Revises: f3149f56d370
Create Date: 2025-09-12 23:44:59.998803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f5867373fc'
down_revision: Union[str, Sequence[str], None] = 'f3149f56d370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=300), nullable=False))
    op.drop_column('projects', 'current_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('current_status', sa.TEXT(), nullable=False))
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
