"""Make conversation model_id nullable for engine default support

Revision ID: dbde08e3eacf
Revises: 5284fb35291f
Create Date: 2025-10-21 12:53:44.078476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbde08e3eacf'
down_revision: Union[str, Sequence[str], None] = '5284fb35291f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('model_id',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.drop_constraint('uq_one_conversation_per_entity', type_='unique')
        batch_op.create_index('idx_active_conversations', ['parent_entity_type', 'parent_entity_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('model_id',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.drop_index('idx_active_conversations')
        batch_op.create_unique_constraint('uq_one_conversation_per_entity', ['parent_entity_type', 'parent_entity_id', 'parent_conversation_id'])
    # ### end Alembic commands ###
