"""Make conversation model_id nullable for engine default support

Revision ID: dbde08e3eacf
Revises: 5284fb35291f
Create Date: 2025-10-21 12:53:44.078476

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbde08e3eacf"
down_revision: str | Sequence[str] | None = "5284fb35291f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("model_id", existing_type=sa.VARCHAR(), nullable=True)
        # Note: uq_one_conversation_per_entity constraint and idx_active_conversations index
        # were already dropped/created in migration 7b1be2f41a34
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("model_id", existing_type=sa.VARCHAR(), nullable=False)
        # Note: uq_one_conversation_per_entity constraint and idx_active_conversations index
        # are handled in migration 7b1be2f41a34
    # ### end Alembic commands ###
