"""Convert parent_entity_type to enum

Revision ID: ebb66080d9c0
Revises: 536d3adbb0a8
Create Date: 2025-09-25 11:14:25.814572

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ebb66080d9c0"
down_revision: str | Sequence[str] | None = "536d3adbb0a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
