"""Initial migration

Revision ID: 9b2a5f2bf10c
Revises: 
Create Date: 2025-08-29 23:09:33.224077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2a5f2bf10c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codebases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.String(length=512), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('context_provider_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_type', sa.String(length=50), nullable=False),
    sa.Column('resource_uri', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('auto_generated_description', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_codebase_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('codebase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codebase_id'], ['codebases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'codebase_id')
    )
    op.create_table('project_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('codebase_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remote_task_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['codebase_id'], ['codebases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('project_conversation_messages')
    op.drop_table('project_codebase_association')
    op.drop_table('projects')
    op.drop_table('context_provider_links')
    op.drop_table('configurations')
    op.drop_table('codebases')
    # ### end Alembic commands ###
